### PR TITLE
Test to reproduce https://github.com/hashicorp/waypoint-plugin-sdk/issues/37

### PR DESCRIPTION
**Pull request by catsby**
This test should reproduce https://github.com/hashicorp/waypoint-plugin-sdk/issues/37

### CODE REVIEW

**Review by briancain — COMMENTED** [review]
Nice, test makes sense to me! Should this PR also fix the test? 🤔

**Comment by catsby** [comment]
@briancain it doesn't have to, but anyone who fixes it is welcome to either push to this branch if they're internal, or fork it to start. I am not current working on a fix, so it's left open as a demonstration of what I believe is an issue.

**Comment by briancain** [comment]
Looks like this test was extracted into https://github.com/hashicorp/waypoint-plugin-sdk/pull/52, so we can probably close this once it's merged!

**Comment by briancain** [comment]
Closing this now since it was fixed in the PR mentioned.

**Pull request closed without merging**
